# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oxmlk}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Robinson"]
  s.date = %q{2009-09-10}
  s.description = %q{OxMlk gives you a simple way to map you ruby objects to XML and then convert one to the other.}
  s.email = %q{hexorx@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/amazon.rb",
     "examples/example.rb",
     "examples/fs_cdr.rb",
     "examples/phrk.rb",
     "examples/posts.rb",
     "examples/twitter.rb",
     "examples/xml/amazon.xml",
     "examples/xml/example.xml",
     "examples/xml/fs_cdr.xml",
     "examples/xml/phrk.xml",
     "examples/xml/posts.xml",
     "examples/xml/twitter.xml",
     "lib/oxmlk.rb",
     "lib/oxmlk/attr.rb",
     "lib/oxmlk/elem.rb",
     "lib/oxmlk/extensions.rb",
     "lib/oxmlk/xml.rb",
     "oxmlk.gemspec",
     "spec/oxmlk/attr_spec.rb",
     "spec/oxmlk/elem_spec.rb",
     "spec/oxmlk_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/xml_spec.rb"
  ]
  s.homepage = %q{http://github.com/hexorx/oxmlk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Object 2 XML kit for ruby}
  s.test_files = [
    "spec/oxmlk/attr_spec.rb",
     "spec/oxmlk/elem_spec.rb",
     "spec/oxmlk_spec.rb",
     "spec/spec_helper.rb",
     "spec/xml_spec.rb",
     "examples/amazon.rb",
     "examples/example.rb",
     "examples/fs_cdr.rb",
     "examples/phrk.rb",
     "examples/posts.rb",
     "examples/twitter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1.0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.1.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.1.0"])
  end
end
